### ISSUE TITLE
multiplart/form-data handle

### ISSUE THREAD

**Issue by farukaziz** [Simonwep/java-express#15]
I am sending file form client like
```
<form method="post" enctype="multipart/form-data">
  <input type="file" name="file">
</form>
```
I have tried with these but not received file.
```
app.post("/", (req, res) -> {
   req.getFormQuery("file");
});
```
How do I receive multipart form data for file upload handle?

**Comment by simonwep** [comment]
See [form-data](https://github.com/Simonwep/java-express#form-data)  - **Currently, File-inputs don't work, if there is an File-input the data won't get parsed!**.
