### ISSUE TITLE
Not necessary to set a Content-Type response header when contentLength = 0

### ISSUE THREAD

**Issue by DinoChiesa** [Simonwep/java-express#27]
If you bracket this line with 
```
if (this.contentLength != 0) { ... } 
```

...then it won't send unnecessary content-type header in the response when the response body is empty.  For example in a typical 302 redirect response.  Or a 204 No Content response.

https://github.com/simonwep/java-express/blob/df473f134e1dc451a5f3187ab0858a765cc2c242/src/main/java/express/http/response/Response.java#L330

**Comment by simonwep** [comment]
Hey! This project is no longer maintained, but if you want, you can open a PR and I'll merge it for others :)

**Comment by DinoChiesa** [comment]
I submitted a PR into masecla22's fork. 

https://github.com/DinoChiesa/java-express/commit/e079e64c6ecb052ffc3ab736dcdf809e0a24209d

**Comment by DinoChiesa** [comment]
Closing - fixed in other fork.
