### ISSUE TITLE
Multiple Middleware like expressjs

### ISSUE THREAD

**Issue by kethan** [Simonwep/java-express#5]
How to use multiple middlewares like expressjs?

app.get('/user/:id', logMiddleware, authMuddleware, ...)

**Comment by simonwep** [comment]
Take a look at the [example](https://github.com/Simonwep/java-express#create-own-middleware) :) For more questions, feel free to ask!

**Comment by kethan** [comment]
> Take a look at the [example](https://github.com/Simonwep/java-express#create-own-middleware) :) For more questions, feel free to ask!

In the example, I see app.use(middleware) but isn't that global? I need a specific like app.get('/users', m1,m2,etc);

**Comment by simonwep** [comment]
Well, as you say. Just do:
```java
app.use("/users", (req, res) -> {}); // Your middleware
app.get("/users", (req, res) -> {}); // Actual handler which gets fired after executed Middleware
```
And yes, the example show's a global middleware. I'll consider to add a route-specific example :)

**Comment by kethan** [comment]
OK thank you it answered my question.
