### ISSUE TITLE
Nice Framework. Why not post it to Maven central?

### ISSUE THREAD

**Issue by DinoChiesa** [Simonwep/java-express#6]
If you make this available on maven central, people will be able to include it into their maven builds easily. 

As it is,  in my maven builds, I must declare a local repo and store the java-express jar file there. This works but it sure would be nice to be able to get the latest version from an externally-hosted maven repo. 

Thanks for the framework.

**Comment by simonwep** [comment]
You're welcome :)
Great idea! I'll take a look! Never really used maven before :/

**Comment by EweLo** [comment]
Yeah. Please add it to Maven Central. I really need it :/

**Comment by simonwep** [comment]
@DinoChiesa  & @EweLoHD 
Is in progress, see https://issues.sonatype.org/browse/OSSRH-47411 :)

**Comment by EweLo** [comment]
Nice thx

**Comment by marty-garage** [comment]
@DinoChiesa 
why not use this:
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
then this:
<dependency>
	    <groupId>com.github.Simonwep</groupId>
	    <artifactId>java-express</artifactId>
	    <version>master-SNAPSHOT</version>
	</dependency>
in your pom

**Comment by simonwep** [comment]
It was to be honest absolutely over-complicated to publish it to Maven, but anyway, Here it is: https://search.maven.org/artifact/com.github.Simonwep/java-express :)
