### ISSUE TITLE
HTML5 History API

### ISSUE THREAD

**Issue by Dmunch04** [Simonwep/java-express#9]
I were told to ask if java-express supports the HTML5 history API? If not, would it be possible to add it?

**Comment by Simonwep** [comment]
I'm not actively working on it anymore (as you can see on the last-commit date), but I may take a look at it in the next days.

**Comment by Dmunch04** [comment]
Sure thing! Sounds good. Thanks a lot

**Comment by Simonwep** [comment]
You could just provide your own fallback, this way you could control how and in which case a fallback should be given:
```java
// Put this line to the very end of you request-handlers to catch all 404 requests
app.all((req, res) -> {

   // Fallback file
   res.send(Paths.get("the/path/to/your/index.html"));
});
```

**Comment by Dmunch04** [comment]
Sorry for late response. It was resolved. Thanks!
